### ISSUE TITLE
Google Analytics / Monster Insights - referral value is set to the Iframe 

### ISSUE THREAD

**Issue by a-larsson** [krokedil/collector-checkout-for-woocommerce#63]
Google Analytics / Monster Insights Pro

Referral value is set to the Iframe url instead of the correct referral source.

The correct referral source is in this case krokedil.nu so it register that but the value is on the Iframe-redirect source.

![skarmavbild 2019-01-09 kl 14 42 51](https://user-images.githubusercontent.com/2573170/50903194-5be74100-141d-11e9-950f-239f54c644dc.png)

**Comment by davidhagg** [comment]
Thank you for filing this issue @a-larsson. Trying to understand this issue. Could you please explain the case in a bit more detail? 

Are you completing a purchase with a redirect URL to a thank you page, and the referral value of that redirect shows the checkout iframe's URL instead of the merchant?

**Comment by davidhagg** [comment]
A fix for this issue in the Collector Checkout was released on February 27 2019. The Checkout now redirects from the loader script instead of the iframe.
