### ISSUE TITLE
Collector exhausts memory

### ISSUE THREAD

**Issue by yratof** [krokedil/collector-checkout-for-woocommerce#69]
Installed 1.3.1 last night, tried to pay for an item and the checkout returned a 500 error. Log shows this:

```
2019/03/06 08:03:36 [error] 19937#19937: *346522 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 16384 bytes) in /master/public/wp/wp-includes/wp-db.php on line 1889
PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 77824 bytes) in /master/public/wp/wp-includes/functions.php on line 3813" while reading response header from upstream, client: x.x.x.x, server: www.pfc.no, request: "GET /checkout/order-received/23744/?key=wc_order_86VoSwwUT7UXf&utm_nooverride=1 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "www.x.x", referrer: "https://www.x.x/checkout/?payment_successful=1&public-token=public-NO-042a9710e0aa2d644fb5afa930353f4dbaad8cabe6617c81"
```

Refreshing the 500 shows the thank you page. So there is a function between paying and thank you that overloads the cpu or creates an endless loop somewhere.

Would love to help diagnose this issue, as my live site is currently facing this problem

**Comment by MichaelBengtsson** [comment]
Hi @yratof 

We did add a function in the latest update that does a DB query to prevent duplicate orders from being created, since this caused an issue with some other websites when customers would return to the confirmation page after the order was placed. We do a similar lookup in some of our other plugins aswell and we dont have this issue. The exact rows are found here: https://github.com/krokedil/collector-checkout-for-woocommerce/blob/master/classes/class-collector-checkout-confirmation.php#L122-L132

This should only be returning the order ids of all orders that happened within 24hours. So this is a relatively small request. It could be the case that your site was on the edge before this update, and this pushed it over by a small amount. You can try and comment out the relevant part if you want to verify this for yourself.

Do you have any information about how much memory usage you had before the update compared to how much is being used at the moment?

**Comment by yratof** [comment]
256mb before, 512mb after — 512mb manages to get the plugin through to the thank you page, but it's a timely effort, about 30 seconds of just checkout loading refreshing, contacting an Icelandic website before contacting a Swedish site, all for confirmations and api calls i presume?

**Comment by MichaelBengtsson** [comment]
@yratof Can you try to downgrade to the older version just to verify that nothing has happened? Because this is not something i can recreate sadly in my enviroment. Just to see that the issue itself started with this release.

**Comment by MichaelBengtsson** [comment]
@yratof Is this still an issue for you? I still cant seem to recreate the issue at all.

**Comment by yratof** [comment]
For now, lets close the issue — Too much time has passed for me to know which issue was causing it
