### ISSUE TITLE
Store credits and giftcards are not calculated.

### ISSUE THREAD

**Issue by danielmalmqvist** [krokedil/collector-checkout-for-woocommerce#80]
Using the official WooCommerce plugin Smart Coupons and using a giftcard does not work. The collector checkout does not take the discount from the giftcard into the calculation of the total price and so it gives me the same price as with no giftcard. It works fully with WooCommerce standard checkout.

**Comment by NiklasHogefjord** [comment]
Hi @danielmalmqvist, I agree that it does work in the standard checkout, but it doesn't automatically work with all payment gateways used since there is no standard/official way for gift certificates to de calculated/withdrawn from the order.

However - we will add support for Smart coupons in the Collector Checkout plugin. A new version should be available later this month.

**Comment by MichaelBengtsson** [comment]
This has a fix now in our develop version and will be released on Monday.
